apps/POKE/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^logout$', views.logout, name = "logout"),
    url(r'^poke$', views.poke, name = "poke"),
]

apps/log_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^register$', views.register, name = "register"),
    url(r'^login$', views.login, name = "login"),
]

pokes_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include("apps.log_reg.urls", namespace = "log_reg")),
    url(r'^pokes/', include("apps.POKE.urls", namespace = "POKE")),
]

apps/POKE/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import Count
from django.db import models
from ..log_reg.models import User

class PokeManager(models.Manager):
	def poke(self, postData):
		poker = User.objects.get(id = postData['poker_id'])
		poked = User.objects.get(id = postData['poked_id'])
		self.create(poker = poker, poked = poked)
		
	def kedirs_pokes(self, id):
		kedir_in = User.objects.get(id = id)
		all_pokes = self.filter(poked = kedir_in)
		count = all_pokes.values('poker').distinct().count()
		return count
	
	def who_poked_kedir(self, id):
		kedir_in = User.objects.get(id = id)
		others = []
		pokers = self.filter(poked = kedir_in).values('poker__alias').distinct()
		for each in pokers:
			others.append(each)
		return others


class Poke(models.Model):
	poker=models.ForeignKey(User,related_name='user_poker',null=True)
	poked=models.ForeignKey(User,related_name='user_poked',null=True)
	created_at=models.DateField(auto_now_add=True)
	updated_at=models.DateField(auto_now=True)
	objects = PokeManager()

apps/log_reg/models.py
from __future__ import unicode_literals

from django.db import models
import bcrypt, re
from datetime import datetime

EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+.[^@\s]+$")


class UserManager(models.Manager):
    def validate_register(self, postData):    
        errors = {}
        
        if not len(postData['name']):
            errors['name'] = "What's your name."
        elif len(postData['name']) < 3:
            errors['name'] = "name field must be at least 3 characters"
        
        if not len(postData['alias']):
            errors['alias'] = "Input your Alias."
        elif len(postData['alias']) < 3:
            errors['alias'] = "Alias field must be at least 3 characters"
        elif self.filter(alias = postData['alias']):
            errors['alias'] = "please enter a new one,Alias is already in use."
        
        if not len(postData['email']):
            errors['email'] = "Input your email."
        elif not re.match(EMAIL_REGEX, postData['email']):
            errors['email'] = "Invalid email! Please input the right format like: kedirzgreat@mail.com"
        elif self.filter(email = postData['email']):
            errors['email'] = "please enter a new Email, this one is already in use."

        if not len(postData['password']):
            errors['password'] = "Password field can not be empty."
        elif len(postData['password']) < 8:
            errors['password'] = "password should be >= 8 characters"
        elif postData['password'] != postData['confirm_pass']:
            errors['confirm_pass'] = "Password you entered is not same as registration password "
        
        if not postData['birthday']:
            errors['birthday'] = "What's your birthday."
        else:
            now = datetime.today().date()
            birthday = datetime.strptime(postData['birthday'], "%Y-%m-%d").date()
            if birthday >= now:
                errors['birthday'] = "Birthday can not be earlier than the current day."

        if len(errors):
            return (False, errors)
        else:
            password = postData['password'].encode()
            hashed = bcrypt.hashpw(password, bcrypt.gensalt())
            self.create(name = postData['name'], alias = postData['alias'], email = postData['email'], password = hashed, birthday = birthday)
            return (True, postData['name'])

    def validate_login(self, postData):
        errors_login = {}
        if not len(postData['email']):
            errors_login['login_email_error'] = "Please provide an email."
        else:
            if not self.filter(email = postData['email']):
                errors_login['login_error'] = "The Email or password you have entered is wrong."
        
        if not len(errors_login):
            user = self.filter(email = postData['email'])
            if not len(postData['password']):
                errors_login['login_password_error'] = "Please provide password."
            else:
                password = postData['password'].encode()
                hashed = self.filter(email = postData['email'])[0].password.encode()
                if not bcrypt.checkpw(password, hashed):
                    errors_login['login_error'] = "Email or password wrong."

        
        if len(errors_login):
            return (False, errors_login)
        else:
            return (True, self.filter(email = postData['email']))


class User(models.Model):
    name = models.CharField(max_length = 255)
    alias = models.CharField(max_length = 255)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    birthday = models.DateField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/POKE/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from ..log_reg.models import User
from .models import *
from django.db.models import Count


def index(request):
    if 'user_name' not in request.session:
        messages.add_message(request, messages.INFO, "you should be logged in first to view this page")
        return redirect('/')
    id = request.session['user_id']
    kedir_in = User.objects.get(id = request.session['user_id'])
    others = User.objects.all().exclude(id = request.session['user_id'])
    kedirs_pokes = Poke.objects.kedirs_pokes(id)
    pokers = Poke.objects.who_poked_kedir(id)
    pok = []
    for each in pokers:
        pok.append(User.objects.get(alias = each['poker__alias']))
    dhuma = []

    for each in pok:
        qabiye = {}
        count = Poke.objects.filter(poker = each, poked = kedir_in).count()
        qabiye['name'] = each.alias
        qabiye['count'] = count
        dhuma.append(qabiye)

    context = {
        'others':others,
        'kedirs_pokes':kedirs_pokes,
        'pokers':dhuma
    }
    return render(request, "POKE/index.html", context)       

def logout(request):
    request.session.flush()
    return redirect('/main')

def poke(request):
    if request.method == 'POST':
        Poke.objects.poke(request.POST)
        return redirect('/pokes/') 

apps/log_reg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages

def index(request):
    print "HI KEDIR"
    return render(request, "log_reg/index.html")

def register(request):
    result = User.objects.validate_register(request.POST)
    if result[0] == False:
        context = {
            'result':result[1]
        }
        return render(request, "log_reg/index.html", context)
    if result[0] == True:
        context = {
            'name': result[1],
            'action': "successfully registered!"
        }
        return render(request, "log_reg/index.html", context)

def login(request):
    result = User.objects.validate_login(request.POST)
    if result[0] == False:
        context = {
            'result':result[1]
        }
        return render(request, "log_reg/index.html", context)
    if result[0] == True:
        request.session['user_name'] = result[1][0].name
        request.session['user_id'] = result[1][0].id
        return redirect('/pokes')

apps/POKE/templates/POKE/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pokes</title>
</head>
<body>
    <a href="{% url 'POKE:logout' %}">Logout</a>
        <h1>Welcome, {{request.session.user_name}}</h1>
        {% if kedirs_pokes > 0 %}
            <p>{{kedirs_pokes}} people poked you!</p>
        {% endif %}
    <br>
    {% for each in pokers|dictsortreversed:'count' %}
        <p>{{each.name}} poked you {{each.count}} times</p>
    {% endfor %}
    <br>
    <h4>People you may want to poke:</h4>
    <table>
        <thead>
            <th>Name</th>
            <th>Alias</th>
            <th>Email Adress</th>
            <th>Poke History</th>
            <th>Action</th>
        </thead>
        {% for each in others %}
            <tr>
                <td>{{each.name}}</td>
                <td>{{each.alias}}</td>
                <td>{{each.email}}</td>
                <td>{{each.user_poked.count}} pokes</td>
                <td>
                    <form action="{% url 'POKE:poke' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="poker_id" value="{{request.session.user_id}}">
                        <input type="hidden" name="poked_id" value="{{each.id}}">
                        <input type="submit" value="Poke!">
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

apps/log_reg/templates/log_reg/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login and Register | Home</title>

</head>
<body>

    <h1>Registration</h1>
    <form action="{% url 'log_reg:register' %}" method="post">
        {% csrf_token %}

                <p>Name:<input type="text" name="name"></p>
                <p id="error">{{result.name}}</p>
                <p>Alias:<input type="text" name="alias"></p>
                <p id="error">{{result.alias}}</p>
                <p>Email:<input type="email" name="email"></p>
                <p id="error">{{result.email}}</p>
                <p>Password:<input type="password" name="password"></p>
                *password should be atleast 8 characters
                <p id="error">{{result.password}}</p>
                <p>Confirm password:<input type="password" name="confirm_pass"></p>
                <p id="error">{{result.confirm_pass}}</p>
                <p>Date of Birth:<input type="date" name="birthday"></p>
                <p id="error">{{result.birthday}}</p>
                <input type="submit" value="Register">
    </form>


    <h1>Login</h1>

    {% for message in messages %}
        <p id="error">{{message}}</p>
    {% endfor %}

    <form action="{% url 'log_reg:login' %}" method="post">
        {% csrf_token %}

                <p>Email:<input type="text" name="email"></p>
                <p id="error">{{result.login_email_error}}</p>
                <p>Password:<input type="password" name="password"></p>
                <p id="error">{{result.login_password_error}}</p>
        <p id="error">{{result.login_error}}</p>
        <input type="submit" value="Login">
    </form>
    <br>
    <p id="success">{{name}} {{action}}</p>
    
</body>
</html>